#!/bin/python3

import logging
import subprocess
import sys

logging.basicConfig(level=logging.ERROR)


def repeat_cmd(cmd: str, count: int) -> None:
    for i in range(1, count + 1):
        logging.info(f"Progress: {i} of {count}")
        logging.debug(f'Try execute command "{cmd}".')
        try:
            subprocess.run(cmd, shell=True, check=True)
        except subprocess.CalledProcessError as e:
            logging.error(f'command execution failed - "{e}".')
            raise e
        logging.debug(f'Executed command "{cmd}".')


if __name__ == "__main__":
    try:
        count = int(sys.argv[1])
    except ValueError:
        logging.error("first argument should be a number.")
        sys.exit(1)
    logging.debug(f"number of executions from args: {count}.")
    cmd = " ".join(sys.argv[2:])
    if not cmd:
        logging.error("cannot find command for repeating.")
        sys.exit(1)
    logging.debug(f"command to execute from args: {cmd}.")
    try:
        repeat_cmd(cmd, count)
    except subprocess.CalledProcessError:
        sys.exit(1)
